# Generated by Django 5.1.6 on 2025-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_active_client_city_client_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Billing Contact Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
