# Generated by Django 5.1.6 on 2025-03-01 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_billing_email_client_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='base_flood_elevation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='projects/{instance.project_number}/contracts/{filename}'),
        ),
        migrations.AddField(
            model_name='project',
            name='flood_map_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='has_legal_contract',
            field=models.BooleanField(default=False, verbose_name='Has Legal Contract'),
        ),
        migrations.AddField(
            model_name='project',
            name='legal_name_for_survey',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal Name for Survey Documents'),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Project Notes'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='property_address',
            field=models.TextField(blank=True, null=True, verbose_name='Property Address'),
        ),
        migrations.AddField(
            model_name='project',
            name='property_tax_parcel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Property Tax Parcel Number'),
        ),
        migrations.AddField(
            model_name='project',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='quoted_time_frame',
            field=models.CharField(blank=True, help_text="e.g., '2 weeks', '1 month'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('field_ready', 'Field Ready'), ('mapping', 'Mapping'), ('pls_review', 'PLS Review'), ('on_hold', 'On Hold'), ('construction_ongoing', 'Construction Ongoing'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='admin', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/{instance.project.project_number}/attachments/{filename}')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, help_text="e.g., 'Office', 'Mobile'", max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_phones', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=50)),
                ('page', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_deeds', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='projects/{instance.project.project_number}/deed_maps/{filename}')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_maps', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBillingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_emails', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ProjectEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_emails', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'email')},
            },
        ),
    ]