# Generated by Django 5.1.6 on 2025-03-02 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_base_flood_elevation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(max_length=50, verbose_name='Crew ID')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_address', models.TextField(blank=True, null=True, verbose_name='Contact Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field Crew',
                'verbose_name_plural': 'Field Crews',
                'ordering': ['crew_id'],
            },
        ),
        migrations.CreateModel(
            name='DataCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100, verbose_name='Model Number')),
                ('has_ts_module', models.BooleanField(default=False, verbose_name='Has TS Module')),
                ('has_gps_module', models.BooleanField(default=False, verbose_name='Has GPS Module')),
                ('software_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='SurvCE/PC Version')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_collectors', to='core.fieldcrew')),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Member Name')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.fieldcrew')),
            ],
        ),
        migrations.CreateModel(
            name='GpsReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100, verbose_name='Model Number')),
                ('receiver_type', models.CharField(choices=[('BASE', 'Base'), ('ROVER', 'Rover')], max_length=5, verbose_name='Receiver Type')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_receivers', to='core.fieldcrew')),
            ],
        ),
        migrations.CreateModel(
            name='MobileHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_model', models.CharField(max_length=100, verbose_name='Make/Model')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('network_name', models.CharField(max_length=50, verbose_name='Network Name')),
                ('network_password', models.CharField(max_length=50, verbose_name='Network Password')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_hotspots', to='core.fieldcrew')),
            ],
        ),
        migrations.CreateModel(
            name='RtkNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=100, verbose_name='Network Name')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtk_networks', to='core.fieldcrew')),
            ],
        ),
        migrations.CreateModel(
            name='TotalStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100, verbose_name='Model Number')),
                ('last_calibration', models.DateField(verbose_name='Last Calibration Date')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_stations', to='core.fieldcrew')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Make')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('license_plate', models.CharField(max_length=20, verbose_name='License Plate')),
                ('tag_renewal_date', models.DateField(verbose_name='Tag Renewal Date')),
                ('last_oil_change', models.DateField(verbose_name='Last Oil Change Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Vehicle Notes')),
                ('crew', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='core.fieldcrew')),
            ],
        ),
    ]
