# Generated by Django 5.1.6 on 2025-03-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fieldcrew_datacollector_crewmember_gpsreceiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=255, verbose_name='Community Name')),
                ('gate_code', models.CharField(max_length=50, verbose_name='Gate Code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gate Code',
                'verbose_name_plural': 'Gate Codes',
                'ordering': ['community_name'],
            },
        ),
    ]
