# Generated by Django 5.1.6 on 2025-03-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fieldcrew_color_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the municipality or community', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this ordinance', null=True)),
                ('is_url', models.BooleanField(default=False, help_text='Whether this is a web link or a PDF document')),
                ('url', models.URLField(blank=True, help_text='Website URL if this is a web link', null=True)),
                ('document', models.FileField(blank=True, help_text='PDF document if this is not a web link', null=True, upload_to='ordinances/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordinance',
                'verbose_name_plural': 'Ordinances',
                'ordering': ['name'],
            },
        ),
    ]
