# Generated by Django 5.1.6 on 2025-03-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ordinance'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geocoded',
            field=models.BooleanField(default=False, help_text='Whether this project has been geocoded'),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
