# Generated by Django 5.1.6 on 2025-03-04 14:23

import core.models.projects
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_geocoded_project_latitude_project_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.projects.project_contract_path),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='file',
            field=models.FileField(upload_to=core.models.projects.project_attachment_path),
        ),
        migrations.AlterField(
            model_name='propertymap',
            name='file',
            field=models.FileField(upload_to=core.models.projects.project_deed_map_path),
        ),
    ]
