# Generated by Django 5.1.6 on 2025-03-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_client_type_clientemail_clientphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flood_zone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flood Zone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('field_ready', 'Field Ready'), ('mapping', 'Mapping'), ('pls_review', 'PLS Review'), ('on_hold', 'On Hold'), ('construction_ongoing', 'Construction Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='admin', max_length=20),
        ),
    ]
